### ISSUE TITLE
Can we export reduxIntegrations directly?

### ISSUE THREAD

**Issue by doelgonzo** [dlombardi/async-operations-manager#2]
I constantly end up using
```
import asyncOperationManager from 'async-operations-manager';
const { reduxIntegration } = asyncOperationManager;
```

But think it would be kind of nice to do
```
import asyncOperationManager, { reduxIntegrations } from 'async-operations-manager';
```

This would help curb some repetitive code with what seems to be a common usecase

**Comment by dlombardi** [comment]
Closed issue after merging https://github.com/dlombardi/async-operations-manager/pull/5
