### ISSUE TITLE
Ability to clear the records for certain actions or action types

### ISSUE THREAD

**Issue by sam1463** [dlombardi/async-operations-manager#4]
Would it be possible to expose a method for removing records for certain actions (based on descriptorId and params)?
This would be like `clearAsyncOperationsManagerState` but only clear part of the state, not the entire state. A use case would be if some action occurs that causes data from certain read operations to become stale (so the current state in AOM for those operations is misleading), then this method would be able to invalidate the records so that the data can be requested as needed (without needing to manually request all data as soon as it becomes stale).

**Comment by dlombardi** [comment]
fixed in https://github.com/dlombardi/async-operations-manager/pull/7
